Difficulty: Normal 
#Easy = Numbers, Normal = Numbers + letters

Language: EN
#SV, EN, FI, FR, DE!

Update: Auto
#Check, Auto, Off

Length: 10
#The length of the random string!

Backup: true
#If the plugin is gonna backup the names.txt or not!

Backup-Time: 1h
#How often the names.txt is gonna be backed up!
#Supported format is: d (day), h (hour), m (minute), s (seconds)

Kick-Time: 2m
#Supported format is: d (day), h (hour), m (minute), s (seconds)